/*

RPI_HAL_GPU_BASE
RPI_HAL_GPU_MEMORY_BASE
RPI_HAL_GPIO_BASE
RPI_HAL_UART0_BASE
RPI_HAL_SYSTIMER_BASE
RPI_HAL_DMA_BASE
RPI_HAL_INT_CTRL_BASE
RPI_HAL_TIMER_BASE
RPI_HAL_MAILBOX_BASE
RPI_HAL_PWM_BASE
RPI_HAL_PWM1_BASE
RPI_HAL_CLK_MANAGER_BASE
RPI_HAL_USB_BASE
RPI_HAL_MPHI_BASE
RPI_HAL_MPHI_END
RPI_HAL_SD_CTL_BASE
RPI_HAL_SD_HOST_BASE
RPI_HAL_POWER_MANAGER_BASE
RPI_HAL_BSC0_BASE
RPI_HAL_BSC1_BASE
RPI_HAL_SPI0_BASE
RPI_HAL_BSC_SPI_SLAVE_BASE
RPI_HAL_AUX_PERIPH_BASE
RPI_HAL_HW_RNG_BASE
RPI_HAL_PCM_I2S_BASE
RPI_HAL_VC4_VCHIQ_BASE
RPI_HAL_VC4_VCHIQ_END
RPI_HAL_HDMI_BASE
RPI_HAL_HD_BASE
RPI_HAL_PHYSICAL_BASE
RPI_HAL_RAM_BASE
RPI_HAL_CSI0_BASE
RPI_HAL_CSI0_END
RPI_HAL_CSI1_BASE
RPI_HAL_CSI1_END

*/

#ifndef _PPDOS_HAL_BCM283X_REGS_
#define _PPDOS_HAL_BCM283X_REGS_

typedef volatile unsigned char rpi_hal_io8_t;
typedef volatile unsigned short rpi_hal_io16_t;
typedef volatile unsigned int rpi_hal_io32_t;

typedef unsigned char rpi_hal_uint8_t;
typedef unsigned short rpi_hal_uint16_t;
typedef unsigned int rpi_hal_uint32_t;

/* Defined bases for different CPUs */
#if defined(PPDOS_USE_BCM2837) || defined(PPDOS_USE_BCM2710A1) || defined(PPDOS_USE_RPI3) || defined(PPDOS_USE_RPI2) || defined(PPDOS_USE_RPI_ZERO_2_W)
#define RPI_HAL_BASE  0x3F000000
#define RPI_HAL_LOAD_FOR 3
#elif defined(PPDOS_USE_BCM7211) || defined(PPDOS_USE_RPI4)
#define RPI_HAL_BASE  0xFE000000
#define RPI_HAL_LOAD_FOR 4
#elif defined(PPDOS_USE_BCM7212) || defined(PPDOS_USE_RPI5)
#define RPI_HAL_BASE  0x107C000000UL
#define RPI_HAL_LOAD_FOR 5
#else
#define RPI_HAL_BASE  0x20000000
#define RPI_HAL_LOAD_FOR 1
#endif

#if defined(PPDOS_USE_BCM7212) || defined(PPDOS_USE_RPI5)
#define RPI_HAL_END   (RPI_HAL_BASE + 0x3FFFFFF)
#else
#define RPI_HAL_END   (RPI_HAL_BASE + 0xFFFFFF)
#endif

#define RPI_HAL_GPU_BASE          0x7E000000
#define RPI_HAL_GPU_CACHED_BASE   0x40000000
#define RPI_HAL_GPU_UNCACHED_BASE 0xC0000000

#if RPI_HAL_LOAD_FOR == 1 && PPDOS_GPU_L2_CACHE_ENABLE
  #define RPI_HAL_GPU_MEMORY_BASE RPI_HAL_GPU_CACHED_BASE
#else
  #define RPI_HAL_GPU_MEMORY_BASE RPI_HAL_GPU_UNCACHED_BASE
#endif

#define RPI_HAL_BUS_ADDRESS(address) (((addr) & ~RPI_HAL_GPU_UNCACHED_BASE) | RPI_HAL_GPU_MEMORY_BASE)

#define RPI_HAL_GPIO_BASE       (RPI_HAL_BASE + 0x200000)
#define RPI_HAL_UART0_BASE      (RPI_HAL_BASE + 0x201000)
#define RPI_HAL_SYSTIMER_BASE   (RPI_HAL_BASE + 0x3000)

#if RPI_HAL_LOAD_FOR <= 4
  #define RPI_HAL_DMA_BASE      (RPI_HAL_BASE + 0x7000)
#else
  #define RPI_HAL_DMA_BASE      0x1000010000UL
#endif

#define RPI_HAL_INT_CTRL_BASE   (RPI_HAL_BASE + 0x8000)
#define RPI_HAL_TIMER_BASE      (RPI_HAL_BASE + 0xB000)

#if RPI_HAL_LOAD_FOR <= 4
  #define RPI_HAL_MAILBOX_BASE  (RPI_HAL_BASE + 0xB880)
#else
  #define RPI_HAL_MAILBOX_BASE  (RPI_HAL_BASE + 0x13880)
#endif

#define RPI_HAL_PWM_BASE        (RPI_HAL_BASE + 0x20C000)
/* Only for RPI 4*/
#define RPI_HAL_PWM1_BASE       (RPI_HAL_BASE + 0x20C800)

#define RPI_HAL_CLK_MANAGER_BASE (RPI_HAL_BASE + 0x101000)
#define RPI_HAL_USB_BASE        (RPI_HAL_BASE + 0x980000)

#define RPI_HAL_MPHI_BASE       (RPI_HAL_BASE + 0x6000)
#define RPI_HAL_MPHI_END        (RPI_HAL_MPHI_BASE + 0xFFF)

#if RPI_HAL_LOAD_FOR <= 4
  #define RPI_HAL_SD_CTL_BASE   (RPI_HAL_BASE + 0x300000)
#else
  #define RPI_HAL_SD_CTL_BASE   0x1000FFF000UL
#endif

#define RPI_HAL_SD_HOST_BASE    (RPI_HAL_BASE + 0x202000)

#if RPI_HAL_LOAD_FOR <= 4
  #define RPI_HAL_POWER_MANAGER_BASE (RPI_HAL_BASE + 0x100000)
#else
  #define RPI_HAL_POWER_MANAGER_BASE (RPI_HAL_BASE + 0x1200000)
#endif

#define RPI_HAL_BSC0_BASE       (RPI_HAL_BASE + 0x205000)
#define RPI_HAL_BSC1_BASE       (RPI_HAL_BASE + 0x804000)
#define RPI_HAL_SPI0_BASE       (RPI_HAL_BASE + 0x204000)
#define RPI_HAL_BSC_SPI_SLAVE_BASE (RPI_HAL_BASE + 0x214000)
#define RPI_HAL_AUX_PERIPH_BASE (RPI_HAL_BASE + 0x215000)
#define RPI_HAL_HW_RNG_BASE     (RPI_HAL_BASE + 0x104000)
#define RPI_HAL_PCM_I2S_BASE    (RPI_HAL_BASE + 0x203000)

#define RPI_HAL_VC4_VCHIQ_BASE  (RPI_HAL_BASE + 0xB840)
#define RPI_HAL_VC4_VCHIQ_END   (RPI_HAL_VC4_VCHIQ_BASE + 0xF)

#if RPI_HAL_LOAD_FOR <= 3
  #define RPI_HAL_HDMI_BASE     (RPI_HAL_BASE + 0x902000)
  #define RPI_HAL_HD_BASE       (RPI_HAL_BASE + 0x808000)
#elif RPI_HAL_LOAD_FOR == 4
  #define RPI_HAL_HDMI_BASE     (RPI_HAL_BASE + 0xF00700)
  #define RPI_HAL_HD_BASE       (RPI_HAL_BASE + 0xF20000)
#else
  #define RPI_HAL_HDMI_BASE     (RPI_HAL_BASE + 0x701400)
  #define RPI_HAL_HD_BASE       (RPI_HAL_BASE + 0x720000)
#endif

#define RPI_HAL_PHYSICAL_BASE (RPI_HAL_BASE + 0xF00F00)

#if RPI_HAL_LOAD_FOR <= 4
    #define RPI_HAL_RAM_BASE    (RPI_HAL_BASE + 0xF01B00)
#else
  #define RPI_HAL_RAM_BASE      (RPI_HAL_BASE + 0x703800)
#endif

#define RPI_HAL_CSI0_BASE       (RPI_HAL_BASE + 0x800000)
#define RPI_HAL_CSI0_END        (RPI_HAL_CSI0_BASE + 0x7FFF)

#define RPI_HAL_CSI1_BASE       (RPI_HAL_BASE + 0x801000)
#define RPI_HAL_CSI1_END        (RPI_KAL_CSI1_BASE + 0x7FFF)

#endif
